# Generated by Django 2.2.4 on 2019-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latest_network_local_ip',
            field=models.GenericIPAddressField(default=None,
                                               null=True,
                                               protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='latest_network_ssid',
            field=models.CharField(default=None, max_length=127, null=True),
        ),
    ]
