# Generated by Django 2.2.4 on 2019-08-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('network_ssid', models.CharField(max_length=127)),
                ('network_local_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.Sensor')),
            ],
        ),
    ]
